[install]
# Use the exact versions specified in package.json
exact = true

# Don't check for updates automatically
check = false

# Cache dependencies globally
cache = true

[install.cache]
# Cache directory for Bun
dir = ".bun"

[dev]
# Automatically clean cache and reinstall on errors
autoClean = true