// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqkXVgzxuRoC615mkfA56gdXtS4S-CNqQ',
    appId: '1:113904571757:web:3142363fdf2c6bc28ef664',
    messagingSenderId: '113904571757',
    projectId: 'scw-tech-check',
    authDomain: 'scw-tech-check.firebaseapp.com',
    storageBucket: 'scw-tech-check.firebasestorage.app',
    measurementId: 'G-DGEM7RG69B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClHzfnoGObO9V6ssvw8K7U9BAfBMImi9A',
    appId: '1:113904571757:android:ceead9e713fc133b8ef664',
    messagingSenderId: '113904571757',
    projectId: 'scw-tech-check',
    storageBucket: 'scw-tech-check.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA--QnwASg9kaHVkdkpcWnbu5wuOyYZfLk',
    appId: '1:113904571757:ios:cfe9a0ad251524218ef664',
    messagingSenderId: '113904571757',
    projectId: 'scw-tech-check',
    storageBucket: 'scw-tech-check.firebasestorage.app',
    iosBundleId: 'com.cpy4.deviceCheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA--QnwASg9kaHVkdkpcWnbu5wuOyYZfLk',
    appId: '1:113904571757:ios:1ce5fd76ef79483a8ef664',
    messagingSenderId: '113904571757',
    projectId: 'scw-tech-check',
    storageBucket: 'scw-tech-check.firebasestorage.app',
    iosBundleId: 'com.example.deviceCheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqkXVgzxuRoC615mkfA56gdXtS4S-CNqQ',
    appId: '1:113904571757:web:d939211cac8055638ef664',
    messagingSenderId: '113904571757',
    projectId: 'scw-tech-check',
    authDomain: 'scw-tech-check.firebaseapp.com',
    storageBucket: 'scw-tech-check.firebasestorage.app',
    measurementId: 'G-5X3RH1CMFS',
  );

}