on:
  push:
    branches: 
      - main
      - preview
jobs:
  deploy_worker:
    name: Deploy Cloudflare Worker
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/tech-check-worker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Deploy Worker
        run: npx wrangler deploy --minify
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  deploy_flutter_app:
    runs-on: ubuntu-latest
    needs: deploy_worker
    defaults:
      run:
        working-directory: apps/tech-check-flutter
    permissions:
      contents: read
      deployments: write
    name: Deploy Flutter App to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Run your project's build step
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install

      - name: Build Flutter web app
        run: flutter build web
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy apps/tech-check-flutter/build/web --project-name=tech-check
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}