name: Deploy Flutter Web App to Cloudflare Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.0'  # Specify your Flutter version

    - name: Install dependencies
      run: flutter pub get

    - name: Build Flutter web app
      run: flutter build web

    - name: Deploy to Cloudflare Pages
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_PROJECT_NAME: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
      run: |
        curl -X POST "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/pages/projects/${CLOUDFLARE_PROJECT_NAME}/deployments" \
          -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
          -H "Content-Type: application/json" \
          --data '{"deployment_trigger": {"type": "ad_hoc"}, "environment": "production", "files": "'"$(find build/web -type f -exec md5sum {} \; | awk '{print $2":"$1}' | sed 's/^/"/;s/:/":"/;s/$/",/;s/^/  {/;s/$/}/' | tr -d '\n' | sed 's/}$/},/' | sed '$s/,$//')"'"}'